In [14]:
# import sys
# import os
# sys.path.append(os.path.abspath('..'))
from config.config import BASE_DIR
from src.analysis import book_analysis

In [15]:
CLEAN_DATA_PATH='D:/Data_Science/TTR_NLP/data/cleaned'

df=book_analysis(CLEAN_DATA_PATH)

In [16]:
df

,book,ttr,mattr,rw_ttr,normalized_ttr,normalized_mattr,normalized_rw_ttr,LRI
0,great_expectations,0.131785,0.827749,0.685866,0.100888,0.238424,0.312006,0.232991
1,hamlet,0.283258,0.819389,0.748017,1.000000,0.129221,1.000000,0.564610
2,huckleberry_finn,0.133223,0.809497,0.718561,0.109423,0.000000,0.673925,0.224062
3,moby_dick,0.188744,0.886052,0.690151,0.438984,1.000000,0.359440,0.695629
4,pride_and_prejudice,0.114788,0.876499,0.657681,0.000000,0.875207,0.000000,0.437604

In [17]:
df.sort_values(by='LRI',ascending=False)

,book,ttr,mattr,rw_ttr,normalized_ttr,normalized_mattr,normalized_rw_ttr,LRI
3,moby_dick,0.188744,0.886052,0.690151,0.438984,1.000000,0.359440,0.695629
1,hamlet,0.283258,0.819389,0.748017,1.000000,0.129221,1.000000,0.564610
4,pride_and_prejudice,0.114788,0.876499,0.657681,0.000000,0.875207,0.000000,0.437604
0,great_expectations,0.131785,0.827749,0.685866,0.100888,0.238424,0.312006,0.232991
2,huckleberry_finn,0.133223,0.809497,0.718561,0.109423,0.000000,0.673925,0.224062

In [18]:
df['LRI'].describe()

count    5.000000
mean     0.430979
std      0.206128
min      0.224062
25%      0.232991
50%      0.437604
75%      0.564610
max      0.695629
Name: LRI, dtype: float64

In [19]:
low_threshold=df['LRI'].quantile(0.33)
high_threshold=df['LRI'].quantile(0.66)

In [20]:
print(low_threshold,high_threshold)

0.2984672514238451 0.5188878296529894